### PR TITLE
Always start y-axes at 0

### PR DESCRIPTION
**Pull request by sophie-h**

### CODE REVIEW

**Comment by klausenbusk** [comment]
Hi, could you provide a example of how this affect the graph?

**Comment by sophie-h** [comment]
Sure (Only makes a difference on graphs with very small numbers)

stats-old
stats-new

**Comment by klausenbusk** [comment]
The scaling is [kinda broken in Chart.js v2.9.x](https://github.com/chartjs/Chart.js/issues/7575), but it is fixed in v3.0.0 ([v3.0.0-beta](https://github.com/chartjs/Chart.js/releases/tag/v3.0.0-beta) was released a hour ago).

I'm not sure this change make sense with the scaling issue fixed, example with `com.valvesoftware.Steam`:
image
With `chart.options.scales.y.min = 0; chart.update()`:
image

I prefer the first graph, what do you think? The [chart.js-v3.0.0 branch](https://github.com/klausenbusk/flathub-stats/tree/chart.js-v3.0.0) contains the relevant code if you want to try it yourself.

**Comment by klausenbusk** [comment]
> I prefer the first graph, what do you think?

I haven't heard anything, so I'm closing the PR. I did cherry-pick the typo fix (https://github.com/klausenbusk/flathub-stats/commit/5f62eb93eccd118922998b905d85289423f8ff3a), thanks!

Feel free to reopen the PR.

**Pull request closed without merging**
